
<Example>:

    featureOne: featureOne
    featureTwo: featureTwo



    ScrollView:
        pos_hint: {'center_x': .5}
        size_hint_x: None
        width: box.width

        do_scroll_x: False
        do_scroll_y: True
        bar_width: 10
        bar_color: app.theme_cls.primary_color
        bar_color_acrive: app.theme_cls.accent_color
        effect_cls: "DampedScrollEffect"
        scroll_type: ['bars']



MDBoxLayout:
    orientation: "vertical"




    MDToolbar:
        title: "Example Tabs"

    MDTabs:
        id: tabs
        on_tab_switch: app.on_tab_switch(*args)

        Tab:
            text: "My Tab 1"

            MDBoxLayout:
                padding: "50dp"
                orientation: 'vertical'
                # size_hint_y: None


                MDLabel:
                    text: "MDLabel is pretty cool to use let's see what this does aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
                    text_size: self.size
                    valign: 'top'
                    font_style: 'H4'
                    theme_text_color: "Custom"
                    text_color: 0, 0, 1, 1
                    pos_hint: {"center_x": .5, "center_y": 1}
                        

            
                MDBoxLayout:
                    padding: "50dp"
                    orientation: 'vertical'
                    # size_hint_y: None
                    adaptive_height: True
                    adaptive_height: True
                    size_hint_y: None
            
                    MDTextField:
                        id: featureOne
                        hint_text: "Helper text on error (press 'Enter')"
                        helper_text: "There will always be a mistake"
                        helper_text_mode: "on_error"
                        padding: "100dp"
                        # text_size: self.size

                    
                    MDTextField:
                        id: featureTwo
                        hint_text: "Helper text on error (press 'Enter')"
                        helper_text: "There will always be a mistake"
                        helper_text_mode: "on_error"
                        padding: "100dp"


                    MDRaisedButton:
                        text: "Submit Features"
                        on_release: app.btn()


                MDBoxLayout:
                    padding: "50dp"
                    orientation: 'vertical'

                    MDRoundFlatIconButton:
                        text: "Open manager"
                        icon: "folder"
                        on_release: app.file_manager_open()            



        Tab:
            text: "My Tab 2"

            MDRoundFlatIconButton:
                text: "Open manager"
                icon: "folder"
                
                on_release: app.file_manager_open()

        Tab:
            text: "My Tab 3"

<Tab>:

    MDFloatLayout:
        padding: "0dp"
        orientation: 'vertical'

    MDLabel:
        id: label
        halign: "auto"
        # padding_y: "0dp"


